import type { InventoryState } from "./types";

export const SPREADSHEET_SOURCE =
  "ציוד לחוות פאנדנגו בצפון — גיליון 9 בספטמבר 2026";

export const seedState: InventoryState = {
  sites: [
    {
      id: "beit-haemek",
      name: "בית העמק",
      updatedAt: "2026-09-09",
      equipment: [
        { id: "bh-barrels", name: "חביות", actual: 30, maxStock: 40 },
        { id: "bh-carts", name: "עגלות לחביות", actual: 11, maxStock: 20 },
        { id: "bh-labels", name: "מדבקות שילוט", actual: 0, maxStock: 20 },
        { id: "bh-gauge-450", name: "מדיד למיכל 450", actual: 5, maxStock: 6 },
        { id: "bh-gauge-451", name: "מדיד למיכל 451", actual: 0, maxStock: 6 },
        { id: "bh-gauge-600", name: "מדיד למיכל 600", actual: 0, maxStock: 6 },
        { id: "bh-gauge-900", name: "מדיד למיכל 900", actual: 0, maxStock: 4 },
        { id: "bh-gauge-1350", name: "מדיד למיכל 1350", actual: 3, maxStock: 4 },
        { id: "bh-gauge-1800", name: "מדיד למיכל 1800", actual: 5, maxStock: 5 },
        { id: "bh-buckets", name: "דליי ריקון", actual: 40, maxStock: 40 },
        { id: "bh-pvc", name: "כפפות PVC", actual: 3, maxStock: 5 },
        { id: "bh-degreaser", name: "מסיר שומן (מארז)", actual: 2, maxStock: 2 },
        { id: "bh-net", name: "רשת יתושים (גליל)", actual: 2, maxStock: 2 },
        { id: "bh-powder", name: "אבקה סופחת", actual: 7, maxStock: 7 },
        { id: "bh-lids", name: "מיכסים לחביות", actual: 0, maxStock: 10 },
        { id: "bh-seals", name: "פלומבות", actual: 6, maxStock: 20 },
        { id: "bh-kaba", name: "מנעולי קאבה", actual: 0, maxStock: 15 },
        { id: "bh-tacho", name: "טכוגרף", actual: 0, maxStock: 2 },
        { id: "bh-spray", name: "ספריי למנעולים", actual: 0, maxStock: 0 },
      ],
      containers: [
        {
          id: "bh-c-30251",
          customerId: "30251",
          customerName: "מקדונלדס - עמיעד",
          containerType: "מיכל ריקון מקדונלדס צר 31",
          plannedDate: "2026-09-11",
          dueDate: null,
          supplied: false,
        },
        {
          id: "bh-c-36583",
          customerId: "36583",
          customerName: "מיכל מרכזי - השוק הטורקי",
          containerType: "מיכל 600",
          plannedDate: null,
          dueDate: null,
          supplied: false,
        },
        {
          id: "bh-c-32906",
          customerId: "32906",
          customerName: "אסדו סטור - טמרה",
          containerType: "מיכל 601 גלגלים",
          plannedDate: null,
          dueDate: null,
          supplied: false,
        },
      ],
    },
    {
      id: "lehavot-haviva",
      name: "להבות חביבה",
      updatedAt: "2026-09-09",
      equipment: [
        { id: "lh-barrels", name: "חביות", actual: 0, maxStock: 40 },
        { id: "lh-carts", name: "עגלות לחביות", actual: 6, maxStock: 20 },
        { id: "lh-labels", name: "מדבקות שילוט", actual: 2, maxStock: 20 },
        { id: "lh-gauge-450", name: "מדיד למיכל 450", actual: 6, maxStock: 6 },
        { id: "lh-gauge-451", name: "מדיד למיכל 451", actual: 6, maxStock: 6 },
        { id: "lh-gauge-600", name: "מדיד למיכל 600", actual: 6, maxStock: 6 },
        { id: "lh-gauge-900", name: "מדיד למיכל 900", actual: 6, maxStock: 6 },
        { id: "lh-gauge-1350", name: "מדיד למיכל 1350", actual: 6, maxStock: 6 },
        { id: "lh-gauge-1800", name: "מדיד למיכל 1800", actual: 6, maxStock: 6 },
        { id: "lh-buckets", name: "דליי ריקון", actual: 0, maxStock: 30 },
        { id: "lh-pvc", name: "כפפות PVC", actual: 1, maxStock: 5 },
        { id: "lh-degreaser", name: "מסיר שומן (מארז)", actual: 0, maxStock: 2 },
        { id: "lh-net", name: "רשת יתושים (גליל)", actual: 1, maxStock: 2 },
        { id: "lh-powder", name: "אבקה סופחת", actual: 2, maxStock: 6 },
        { id: "lh-lids", name: "מיכסים לחביות", actual: 0, maxStock: 10 },
        { id: "lh-seals", name: "פלומבות", actual: 0, maxStock: 50 },
        { id: "lh-kaba", name: "מנעולי קאבה", actual: 0, maxStock: 10 },
        { id: "lh-rags", name: "סחבות (שק)", actual: 1, maxStock: 1 },
        { id: "lh-urea", name: "אוריאה", actual: 0, maxStock: 4 },
        { id: "lh-cloth-gloves", name: "כפפות בד", actual: 0, maxStock: 2 },
        { id: "lh-bucket-lids", name: "מכסה לדליים", actual: 10, maxStock: 10 },
        { id: "lh-beach-bags", name: "שקיות גדולות חוף", actual: 0, maxStock: 0 },
        { id: "lh-road-broom", name: "מטאטא כביש", actual: 0, maxStock: 1 },
        { id: "lh-broom", name: "מטאטא", actual: 0, maxStock: 1 },
        { id: "lh-brush", name: "מברשת קטנה לאוטו", actual: 0, maxStock: 0 },
        { id: "lh-paper", name: "נייר סופג (חבילה)", actual: 1, maxStock: 2 },
        { id: "lh-wipes", name: "מגבונים עם אלכוג׳ל", actual: 4, maxStock: 4 },
        { id: "lh-tacho", name: "טכוגרף", actual: 0, maxStock: 1 },
      ],
      containers: [
        {
          id: "lh-c-36588",
          customerId: "36588",
          customerName: "בורגראנץ׳ - נתניה",
          containerType: "עגלה ל 2 דליים",
          plannedDate: null,
          dueDate: null,
          supplied: false,
        },
      ],
    },
    {
      id: "kfar-hasidim",
      name: "כפר חסידים",
      updatedAt: "2026-05-20",
      equipment: [
        { id: "kh-barrels", name: "חביות", actual: 7, maxStock: 32 },
        { id: "kh-carts", name: "עגלות לחביות", actual: 3, maxStock: 20 },
        { id: "kh-bucket-carts", name: "עגלות לדליים", actual: 0, maxStock: 2 },
        { id: "kh-mcdonalds", name: "מיכל ריקון מקד׳", actual: 0, maxStock: 2 },
        { id: "kh-spill-240", name: "מאצרה למיכל 240", actual: 0, maxStock: 1 },
        { id: "kh-spill-450", name: "מאצרה למיכל 450", actual: 0, maxStock: 1 },
        { id: "kh-spill-600", name: "מאצרה למיכל 600", actual: 0, maxStock: 1 },
        { id: "kh-spill-900", name: "מאצרה למיכל 900", actual: 0, maxStock: 1 },
        { id: "kh-buckets", name: "דליי ריקון", actual: 2, maxStock: 30 },
        { id: "kh-pvc", name: "כפפות PVC", actual: 1, maxStock: 5 },
        { id: "kh-degreaser", name: "מסיר שומן (מארז)", actual: 2, maxStock: 1 },
        { id: "kh-net", name: "רשת יתושים (גליל)", actual: 0, maxStock: 2 },
        { id: "kh-powder", name: "אבקה סופחת", actual: 1, maxStock: 6 },
        { id: "kh-kaba", name: "מנעולי קאבה", actual: 10, maxStock: 10 },
        { id: "kh-label-barrel", name: "מדבקת שילוט לחבית", actual: 30, maxStock: 30 },
        { id: "kh-clear-label", name: "מדבקה שקופה לחבית", actual: 30, maxStock: 30 },
        { id: "kh-knife", name: "סכין יפנית", actual: 1, maxStock: 1 },
        { id: "kh-eitan", name: "מילוי איתן", actual: 0, maxStock: 1 },
        { id: "kh-lids", name: "מיכסים לחביות", actual: 0, maxStock: 10 },
        { id: "kh-rags", name: "סחבות", actual: 2, maxStock: 3 },
      ],
      containers: [],
    },
  ],
};

export function cloneSeed(): InventoryState {
  return structuredClone(seedState);
}
