import type { AppStore, EquipmentItem } from "./types";

export const DEMO_USERS = [
  "אריאל",
  "מיכל",
  "יוסי",
  "נועה",
  "דוד",
  "רחל",
  "עמית",
  "תמר",
  "איתן",
  "שירה",
];

function eq(id: string, name: string, actual: number, maxStock: number): EquipmentItem {
  return {
    id,
    name,
    actual,
    maxStock,
    toComplete: Math.max(0, maxStock - actual),
  };
}

export function createSeedStore(): AppStore {
  return {
    users: [...DEMO_USERS],
    loads: [],
    reports: [],
    farms: [
      {
        id: "beit-haemek",
        name: "בית העמק",
        updatedAt: "2026-09-09",
        equipment: [
          eq("bh-barrels", "חביות", 30, 40),
          eq("bh-carts", "עגלות לחביות", 11, 20),
          eq("bh-labels", "מדבקות שילוט", 0, 20),
          eq("bh-gauge-450", "מדיד למיכל 450", 5, 6),
          eq("bh-gauge-451", "מדיד למיכל 451", 0, 6),
          eq("bh-gauge-600", "מדיד למיכל 600", 0, 6),
          eq("bh-gauge-900", "מדיד למיכל 900", 0, 4),
          eq("bh-gauge-1350", "מדיד למיכל 1350", 3, 4),
          eq("bh-gauge-1800", "מדיד למיכל 1800", 5, 5),
          eq("bh-buckets", "דליי ריקון", 40, 40),
          eq("bh-pvc", "כפפות PVC", 3, 5),
          eq("bh-degreaser", "מסיר שומן (מארז)", 2, 2),
          eq("bh-net", "רשת יתושים (גליל)", 2, 2),
          eq("bh-powder", "אבקה סופחת", 7, 7),
          eq("bh-lids", "מיכסים לחביות", 0, 10),
          eq("bh-seals", "פלומבות", 6, 20),
          eq("bh-kaba", "מנעולי קאבה", 0, 15),
          eq("bh-tacho", "טכוגרף", 0, 2),
          eq("bh-spray", "ספריי למנעולים", 0, 0),
        ],
        containers: [
          {
            id: "bh-c-30251",
            customerId: "30251",
            customerName: "מקדונלדס - עמיעד",
            containerType: "מיכל ריקון מקדונלדס צר 31",
            supplied: false,
          },
          {
            id: "bh-c-36583",
            customerId: "36583",
            customerName: "מיכל מרכזי - השוק הטורקי",
            containerType: "מיכל 600",
            supplied: false,
          },
          {
            id: "bh-c-32906",
            customerId: "32906",
            customerName: "אסדו סטור - טמרה",
            containerType: "מיכל 601 גלגלים",
            supplied: false,
          },
        ],
      },
      {
        id: "lehavot-haviva",
        name: "להבות חביבה",
        updatedAt: "2026-09-09",
        equipment: [
          eq("lh-barrels", "חביות", 0, 40),
          eq("lh-carts", "עגלות לחביות", 6, 20),
          eq("lh-labels", "מדבקות שילוט", 2, 20),
          eq("lh-gauge-450", "מדיד למיכל 450", 6, 6),
          eq("lh-gauge-451", "מדיד למיכל 451", 6, 6),
          eq("lh-gauge-600", "מדיד למיכל 600", 6, 6),
          eq("lh-gauge-900", "מדיד למיכל 900", 6, 6),
          eq("lh-gauge-1350", "מדיד למיכל 1350", 6, 6),
          eq("lh-gauge-1800", "מדיד למיכל 1800", 6, 6),
          eq("lh-buckets", "דליי ריקון", 0, 30),
          eq("lh-pvc", "כפפות PVC", 1, 5),
          eq("lh-degreaser", "מסיר שומן (מארז)", 0, 2),
          eq("lh-net", "רשת יתושים (גליל)", 1, 2),
          eq("lh-powder", "אבקה סופחת", 2, 6),
          eq("lh-lids", "מיכסים לחביות", 0, 10),
          eq("lh-seals", "פלומבות", 0, 50),
          eq("lh-kaba", "מנעולי קאבה", 0, 10),
          eq("lh-rags", "סחבות (שק)", 1, 1),
          eq("lh-urea", "אוריאה", 0, 4),
          eq("lh-cloth-gloves", "כפפות בד", 0, 2),
          eq("lh-bucket-lids", "מכסה לדליים", 10, 10),
          eq("lh-beach-bags", "שקיות גדולות חוף", 0, 0),
          eq("lh-road-broom", "מטאטא כביש", 0, 1),
          eq("lh-broom", "מטאטא", 0, 1),
          eq("lh-brush", "מברשת קטנה לאוטו", 0, 0),
          eq("lh-paper", "נייר סופג (חבילה)", 1, 2),
          eq("lh-wipes", "מגבונים עם אלכוג׳ל", 4, 4),
          eq("lh-tacho", "טכוגרף", 0, 1),
        ],
        containers: [
          {
            id: "lh-c-36588",
            customerId: "36588",
            customerName: "בורגראנץ׳ - נתניה",
            containerType: "עגלה ל 2 דליים",
            supplied: false,
          },
        ],
      },
      {
        id: "kfar-hasidim",
        name: "כפר חסידים",
        updatedAt: "2026-05-20",
        equipment: [
          eq("kh-barrels", "חביות", 7, 32),
          eq("kh-carts", "עגלות לחביות", 3, 20),
          eq("kh-bucket-carts", "עגלות לדליים", 0, 2),
          eq("kh-mcdonalds", "מיכל ריקון מקד׳", 0, 2),
          eq("kh-spill-240", "מאצרה למיכל 240", 0, 1),
          eq("kh-spill-450", "מאצרה למיכל 450", 0, 1),
          eq("kh-spill-600", "מאצרה למיכל 600", 0, 1),
          eq("kh-spill-900", "מאצרה למיכל 900", 0, 1),
          eq("kh-buckets", "דליי ריקון", 2, 30),
          eq("kh-pvc", "כפפות PVC", 1, 5),
          eq("kh-degreaser", "מסיר שומן (מארז)", 2, 1),
          eq("kh-net", "רשת יתושים (גליל)", 0, 2),
          eq("kh-powder", "אבקה סופחת", 1, 6),
          eq("kh-kaba", "מנעולי קאבה", 10, 10),
          eq("kh-label-barrel", "מדבקת שילוט לחבית", 30, 30),
          eq("kh-clear-label", "מדבקה שקופה לחבית", 30, 30),
          eq("kh-knife", "סכין יפנית", 1, 1),
          eq("kh-eitan", "מילוי איתן", 0, 1),
          eq("kh-lids", "מיכסים לחביות", 0, 10),
          eq("kh-rags", "סחבות", 2, 3),
        ],
        containers: [],
      },
    ],
  };
}
